### ISSUE TITLE
Missing css

### ISSUE THREAD

**Issue by picaosgeo** [Gaia3D/mago3d-CMS#102]
Some css files do not exist.
At "mago3d-admin\src\main\webapp\WEB-INF\views\config\list-db-backup-log.jsp"
 
	<link type="text/css" rel="stylesheet" href="/css/ko/layout.css" />
	<link type="text/css" rel="stylesheet" href="/css/ko/common.css" />
	<link type="text/css" rel="stylesheet" href="/css/ko/admin.css" />

**Comment by cheonjeongdae** [comment]
Sorry.
That's because there's a mix of sources in development.
Its functionality has not been developed yet.
I will copy & paste dumy functions to be developed in the future.
It was born.
You can ignore it.
Sorry for the confusion.
