### ISSUE TITLE
/config/modify-policy.do has null-pointer error, if default project is removed

### ISSUE THREAD

**Issue by naokiueda** [Gaia3D/mago3d-CMS#118]
About config/modify-policy.do

When "시작시 로딩 프로젝트" is set to some project(s), and if its project is deleted.
Opening "/config/modify-policy.do" result in NullPointer error in Java, and browser get error.

To recover, erase "geo_data_default_projects" from policy table.

Maybe, delete "geo_data_default_projects" from "modify-policy.do" screen first, then remove project cause no error.

**Comment by cheonjeongdae** [comment]
ありがとうございます。
了解しました。
Buggerですね。
修正します。
